name: calling workflow

on:

  push:

    branches: [ "main" ]
 
  workflow_dispatch:
 
jobs:

  job1:
                     # Reuses a workflow from another repo
    uses:  CanarysPlayground/actions-3.0/.github/workflows/reuse.yml@main
 
  job2:

    runs-on: ubuntu-latest

    needs: job1       # job2 runs only after job1 completes

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Run build

        run: echo "Building the project..."
